### ISSUE TITLE
 Call to undefined function simplexml_load_string()

### ISSUE THREAD

**Issue by wdssmq** [alastairhm/alpine-lighttpd-php#2]

**Comment by alastairhm** [comment]
Any information that you can provide?

**Comment by wdssmq** [comment]
It seems that this function is installed from php-simplexml instead of php-xml.

**Comment by alastairhm** [comment]
If you want to submit a pull request with a fix I will merge it in and rebuild. Or I will have a look when I can, thank you for reaching out.

**Comment by alastairhm** [comment]
I've added that simplexml module, you can test it with this image `alastairhm/alpine-lighttpd-php:test`

**Comment by alastairhm** [comment]
New Docker version pushed as `alastairhm/alpine-lighttpd-php:3.14.1` and `alastairhm/alpine-lighttpd-php:latest`.

Thank you.
